/* Generated by Together */

package com.teamsun.core.utils;

import java.io.Serializable;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;

import javax.transaction.SystemException;

import com.teamsun.core.utils.BeanUtils;
import com.teamsun.core.utils.XMLSerializable;


/**
 * ����ܵ���ݶ���ӿ�
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: Best-Star</p>
 * @author Guojf
 * @version 1.0
 */

public abstract class BasicBean
    extends XMLSerializable
    implements Cloneable, Serializable {

    private int pageSize = 0;
    private long pageCount = 0;
    private long rowCount = 0;
    private long pageNum = 0;
    public static final int NONE = 0;
    public static final int INSERT = 1;
    public static final int UPDATE = 2;
    public static final int DELETE = 3;
    public static final boolean UPDATE_ALL = true;
    public static final boolean UPDATE_NOTNULL = false;
    private int action = 0;
    private boolean updateType = UPDATE_ALL;

    /**
     *
     * @return
     */
    public abstract Object[] getPrimaryKey();

    /**
     *
     * @return
     */
    public abstract String getAutoId();

    /**
     *
     * @return
     */
    public abstract String getTablename();

    /**
     *
     * @return
     */
    public long getPageCount() {
        return pageCount;
    }

    /**
     *
     * @param pageCount
     */
    public void setPageCount(long pageCount) {
        this.pageCount = pageCount;
    }

    /**
     *
     * @return
     */
    public long getPageNum() {
        return pageNum;
    }

    /**
     *
     * @param pageNum
     */
    public void setPageNum(long pageNum) {
        this.pageNum = pageNum;
    }

    /**
     *
     * @return
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     *
     * @param pageSize
     */
    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    /**
     *
     * @return
     */
    public long getRowCount() {
        return rowCount;
    }

    /**
     *
     * @param rowCount
     */
    public void setRowCount(long rowCount) {
        this.rowCount = rowCount;
    }

    /**
     *
     * @return
     */
    public int getAction() {
        return action;
    }

    /**
     *
     * @param action
     */
    public void setAction(int action) {
        this.action = action;
    }

    /**
     *
     * @return
     */
    public Collection getPropertyNames() {
        return BeanUtils.getProperties(this.getClass());
    }

    /**
     *
     * @return
     * @throws SystemException
     */
    public Map getPropertyValuesMap() throws SystemException {
        Vector properties = (Vector) getPropertyNames();
        HashMap map = new HashMap();
        for (int i = 0; i < properties.size(); i++) {
            String name = (String) properties.get(i);
            map.put(name, getPropertyValue(name));
        }
        return map;
    }

    /**
     *
     * @param propertyName
     * @return
     * @throws SystemException
     */
    public Object getPropertyValue(String propertyName) throws SystemException {
        return BeanUtils.getPropertyValue(this, propertyName);
    }

    /**
     *
     * @param propertyName
     * @param value
     * @throws SystemException
     */
    public void putPropertyValue(String propertyName, Object value) throws
        SystemException {
        BeanUtils.setPropertyValue(this, propertyName, value);
    }

    /**
     *
     * @return
     */
    public boolean getUpdateType() {
        return updateType;
    }

    /**
     *
     * @param updateType
     */
    public void setUpdateType(boolean updateType) {
        this.updateType = updateType;
    }
}
